package mcinterface1211;
import net.minecraft.core.registries.Registries;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

import minecrafttransportsimulator.items.components.AItemBase;
import minecrafttransportsimulator.mcinterface.IInterfaceCore;
import minecrafttransportsimulator.mcinterface.IWrapperItemStack;
import minecrafttransportsimulator.mcinterface.IWrapperNBT;
import minecrafttransportsimulator.mcinterface.InterfaceManager;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.TagKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.fml.loading.FMLEnvironment;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.ModList;

class InterfaceCore implements IInterfaceCore {
    protected static final Map<String, List<BuilderItem>> taggedItems = new HashMap<>();

    @Override
    public boolean isGameFlattened() {
        return true;
    }

    @Override
    public boolean isModPresent(String modID) {
        return ModList.get().isLoaded(modID);
    }

    @Override
    public boolean isFluidValid(String fluidID) {
        for (ResourceLocation location : BuiltInRegistries.FLUID.keySet()) {
            if (location.getPath().equals(fluidID)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String getModName(String modID) {
        return ModList.get().getModContainerById(modID).get().getModInfo().getDisplayName();
    }
    
    @Override
    public InputStream getPackResource(String resource) {
        int assetsIndexEnd = resource.indexOf("assets/") + "assets/".length();
        int modIDEnd = resource.indexOf("/", assetsIndexEnd + 1);
        String modID = resource.substring(assetsIndexEnd, modIDEnd);
        Optional<? extends ModContainer> optional = ModList.get().getModContainerById(modID);
        if (optional.isPresent()) {
            ModContainer container = optional.get();

            // Strategy 1: Try the container's classloader (original approach)
            ClassLoader containerClassLoader = container.getClass().getClassLoader();
            InputStream stream = containerClassLoader.getResourceAsStream(resource);
            if (stream != null) {
                return stream;
            }

            // Strategy 2: Try Thread context classloader
            try {
                ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
                stream = contextClassLoader.getResourceAsStream(resource);
                if (stream != null) {
                    return stream;
                }
            } catch (Exception e) {
                // Continue to fallback
            }
        }

        // Fallback: Try loading from InterfaceManager class (for dev builds and mod resources)
        return InterfaceManager.class.getResourceAsStream(resource);
    }


    @Override
    public void logError(String message) {
        InterfaceLoader.LOGGER.error("MTSERROR: " + message);
    }

    @Override
    public void logErrorMain(String message) {
        InterfaceLoader.LOGGER.error("FMOD SYSTEM ERROR: " + message);
    }

    @Override
    public void logInfo(String message) {
        InterfaceLoader.LOGGER.info("FMOD SYSTEM INFO: " + message);
    }

    @Override
    public IWrapperNBT getNewNBTWrapper() {
        return new WrapperNBT();
    }

    @Override
    public IWrapperItemStack getAutoGeneratedStack(AItemBase item, IWrapperNBT data) {
        WrapperItemStack newStack = new WrapperItemStack(new ItemStack(BuilderItem.itemMap.get(item)));
        newStack.setData(data);
        return newStack;
    }

    @Override
    public IWrapperItemStack getStackForProperties(String name, int meta, int qty) {
        Item item = BuiltInRegistries.ITEM.get(ResourceLocation.tryParse(name));
        if (item != null) {
            return new WrapperItemStack(new ItemStack(item, qty));
        } else {
            return new WrapperItemStack(ItemStack.EMPTY.copy());
        }
    }

    @Override
    public String getStackItemName(IWrapperItemStack stack) {
        return BuiltInRegistries.ITEM.getKey(((WrapperItemStack) stack).stack.getItem()).toString();
    }

    @Override
    public boolean isOredictMatch(IWrapperItemStack stackA, IWrapperItemStack stackB) {
        return !((WrapperItemStack) stackA).stack.isEmpty() && ((WrapperItemStack) stackA).stack.is(((WrapperItemStack) stackB).stack.getItem());
    }

    @SuppressWarnings("deprecation")
    @Override
    public List<IWrapperItemStack> getOredictMaterials(String oreName, int stackSize) {
        //Convert to lowercase in case we are camelCase from oreDict systems.
        //Also do a bunch of stupid stream crap, cause hashmaps are clearly not made to lookup things...
        String lowerCaseOre = oreName.toLowerCase(Locale.ROOT);
        List<IWrapperItemStack> stacks = new ArrayList<>();
        Stream<TagKey<Item>> tagStream = BuiltInRegistries.ITEM.getTagNames().filter(tagKey -> tagKey.location().getPath().equals(lowerCaseOre));
        tagStream.forEach(tagKey -> {
            for (Holder<Item> holder : BuiltInRegistries.ITEM.getTagOrEmpty(tagKey)) {
                stacks.add(new WrapperItemStack(new ItemStack(holder.value(), stackSize)));
            }
        });
        //Couldn't find normal OreDict, check our internal stuff.
        if (stacks.isEmpty()) {
            List<BuilderItem> items = taggedItems.get(lowerCaseOre);
            if (items != null) {
                items.forEach(item -> stacks.add(new WrapperItemStack(new ItemStack(item, stackSize))));
            }
        }

        return stacks;
    }
}
