modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/DonBruce64/MinecraftTransportSimulator/issues"

# Mod Info
[[mods]]
modId="mts"
version="${file.jarVersion}"
displayName="Immersive Vehicles (formerly MTS)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator"
logoFile="vingette.png"
credits="Don Bruce & The Modeling Crew."
description='''
Realistic planes and cars for Minecraft!
'''
[[dependencies.mts]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.mts]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"
